# Generated by Django 5.2.5 on 2025-09-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('frame_type', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('atk', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('race', models.CharField(max_length=100)),
                ('attribute', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=255)),
                ('set_code', models.CharField(max_length=50)),
                ('set_rarity', models.CharField(max_length=100)),
                ('set_rarity_code', models.CharField(max_length=20)),
                ('set_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_set', to='scraping.card')),
            ],
            options={
                'db_table': 'card_set',
            },
        ),
    ]
