# Generated by Django 5.2.5 on 2025-09-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardmarket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tcgplayer_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ebay_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amazon_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coolstuffinc_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_prices', to='scraping.card')),
            ],
        ),
    ]
