# Generated by Django 5.2.5 on 2025-09-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_cardprice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cardprice',
            table='card_price',
        ),
    ]
